### ISSUE TITLE
Uninitialized constant DataShift:Logging

### ISSUE THREAD

**Issue by jetsgit** [autotelik/datashift_spree#1]
Hi Tom,

with new install using jRuby 1.7.0.preview and Spree 1.1.2, getting following error when 

   bundle exec thor list datashift_spree

WARNING: unable to load thorfile "/home/jet/.rvm/gems/jruby-1.7.0.preview1@Spree_1.1.2/bundler/gems/datashift_spree-51d917967aff/lib/thor/spree/bootstrap_cleanup.thor": uninitialized constant DataShift::Logging

Jet

**Comment by raulpopadineti** [comment]
:+1:

**Comment by sunilkalyan08** [comment]
I am facing the same issue "unable to load thorfile "/home/Documents/make/lib/tasks/sample.thor": uninitialized constant DataShift::Logging" 

require 'thor'
require 'datashift'
