### ISSUE TITLE
import multiple images with whitespace between pipe not working

### ISSUE THREAD

**Issue by Michael1969** [autotelik/datashift_spree#15]
Hi,

this works: import_images/rails.png|import_images/rails1.png

this not: import_images/rails.png | import_images/rails1.png

thanks

**Comment by connecticus** [comment]
Hi Michael, how do you fix this issue?

**Comment by Michael1969** [comment]
last column on csv is images

"image1.jpg:Otago's Wildlife Cruise|image2.jpg:description|image3.jpg:description of image|"  ....
no space between pipe | sperator

**Comment by connecticus** [comment]
Thank you, Michael
Here is my file [https://gist.github.com/connecticus/674f4430166b23605fe1](url)
Is it correct?

**Comment by Michael1969** [comment]
this csv worked for me:
sku,name,price,cost_price,currency,tax_category_id,shipping_category_id,meta_description,meta_keywords,description,taxons,available_on,images
NSNSSWILSONGUIDED,"Beaches, Bays and Seals",0.0,0.0,NZD-100,3,3,"Beaches, Bays and Seals","Beaches, Bays and Seals","Enjoy the clear waters, golden beach",Attractions>Nelson/Tasman,2016-03-01 13:07:53 +1300,"images/Supplier_WILSON/Option_NSNSSWILSONGUIDED/NSNSSWILSONGUIDED.jpg:Beaches, Bays and Seals

**Comment by connecticus** [comment]
I am put in last Images column something like this -  import_images/rails.png|import_images/rails1.png but no luck.

If I make additional Images column - everything ok. But solution with separator (like was shown by you) - better for me.

Can you please share you gemfile

Thank you!
