### ISSUE TITLE
Uninitialized constant DataShift::SpreeEcom::ImageLoader::ModelMethodsManager (NameError)

### ISSUE THREAD

**Issue by dangerdogz** [autotelik/datashift_spree#44]
Since today I can't run :  bundle exec thor datashift_spree:load:attach_images

**Sample command :**

bundle exec thor datashift_spree:load:attach_images -i db/products/csv/images.csv

I'm running the latest version with Spree 2.4 and Rails 4.1.8

**From GEMFILE** 

gem 'datashift', github: 'autotelik/datashift'
gem 'datashift_spree', github: 'autotelik/datashift_spree', :branch => 'master'

**From GEMFILE.lock** 

  remote: git://github.com/autotelik/datashift_spree.git
  revision: 37f79a7bf671218a205bc6ee12999e2acf29c80b
  branch: master
  specs:
    datashift_spree (0.6.0)
      datashift (~> 0.15, >= 0.15.0)
      mechanize (~> 2.6, >= 2.6.0)

**The problem is visible on a clean install of Spree with nothing but datashift and default Spree 2.4 config**

I remember using it about a month ago without any issues.

Any idea?
Stacktrace :
/Users/lawebshopimac/.rvm/gems/ruby-2.1.2@mchoc/bundler/gems/datashift_spree-37f79a7bf671/lib/loaders/spree/image_loader.rb:28:in `initialize': uninitialized constant DataShift::SpreeEcom::ImageLoader::ModelMethodsManager (NameError)
	from /Users/lawebshopimac/.rvm/gems/ruby-2.1.2@mchoc/bundler/gems/datashift_spree-37f79a7bf671/lib/thor/spree/products_images.thor:83:in `new'
	from /Users/lawebshopimac/.rvm/gems/ruby-2.1.2@mchoc/bundler/gems/datashift_spree-37f79a7bf671/lib/thor/spree/products_images.thor:83:in `attach_images'
	from /Users/lawebshopimac/.rvm/gems/ruby-2.1.2@mchoc/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/lawebshopimac/.rvm/gems/ruby-2.1.2@mchoc/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/lawebshopimac/.rvm/gems/ruby-2.1.2@mchoc/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/lawebshopimac/.rvm/gems/ruby-2.1.2@mchoc/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/lawebshopimac/.rvm/gems/ruby-2.1.2@mchoc/gems/thor-0.19.1/lib/thor/runner.rb:36:in `method_missing'
	from /Users/lawebshopimac/.rvm/gems/ruby-2.1.2@mchoc/gems/thor-0.19.1/lib/thor/command.rb:29:in `run'
	from /Users/lawebshopimac/.rvm/gems/ruby-2.1.2@mchoc/gems/thor-0.19.1/lib/thor/command.rb:126:in `run'
	from /Users/lawebshopimac/.rvm/gems/ruby-2.1.2@mchoc/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/lawebshopimac/.rvm/gems/ruby-2.1.2@mchoc/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/lawebshopimac/.rvm/gems/ruby-2.1.2@mchoc/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/lawebshopimac/.rvm/gems/ruby-2.1.2@mchoc/gems/thor-0.19.1/bin/thor:6:in `<top (required)>'
	from /Users/lawebshopimac/.rvm/gems/ruby-2.1.2@mchoc/bin/thor:23:in `load'
	from /Users/lawebshopimac/.rvm/gems/ruby-2.1.2@mchoc/bin/thor:23:in `<main>'

**Comment by joeswann** [comment]
Just ran into this same issue, did you find a solution?
