### ISSUE TITLE
Paperclip not working for spree 3?

### ISSUE THREAD

**Issue by kaesaeki** [autotelik/datashift_spree#57]
Is this function working correctly?

I cannot seem to get it working. The "f" option gives me a name error.

bundle exec thor datashift:paperclip:attach -a Spree::Image -k Spree::Variant -f sku --attach-to-find-by-field sku -i /home/ubuntu/workspace/public/spree/images/

Using Field sku for lookup
/usr/local/rvm/gems/ruby-2.3.0/gems/datashift-0.16.0/lib/thor/paperclip.thor:105:in `attach': uninitialized constant Thor::Sandbox::Datashift::Paperclip::ModelMapper (NameError)

**Comment by autotelik** [comment]
hi

-f is the field on Spree::Variant  the attachment (image) attaches to i.e the associaiton that stores the images  - so looking at latest Spree 3
https://github.com/spree/spree/blob/master/core/app/models/spree/variant.rb

has_many :images, -> { order(:position) }, as: :viewable, dependent: :destroy, class_name: "Spree::Image"

so you want -f images

I have just tested the following 

```
thor datashift:paperclip:attach -a Spree::Image -k Spree::Variant -f images --attach-to-find-by-field sku -i tmp/images/ --split_file_name_on _
```

where I had  images named to match 4 skus with '_' as a seperator

>ls tmp/images/
DEMO_ROR-00011_ror.jpeg  DEMO_ROR-00012.jpeg  DEMO_RUB-00001.jpeg  ROR-00016_blalblahblah.jpeg

And all good ...

```
Using Field sku to lookup matching [Spree::Variant]
Logging going to target [log/datashift.log]
Created 4 / 4 attachments of type Spree::Image attached to Spree::Variant
```

N.B This was using Latest  work -  currently under new branch 'split_into_concerns'

This will very shortly become master but you should definitely specify this branch in Gemfile for now

**Comment by autotelik** [comment]
Looks like your still using installed Gem :  /usr/local/rvm/gems/ruby-2.3.0/gems/**datashift-0.16.0**

**Comment by autotelik** [comment]
my Gemfile looks like

gem 'datashift', github: 'autotelik/datashift', branch: 'split_into_concerns'

And the output should report correctly using sku (not - Using Field **images** for lookup)

Using Field **sku** to lookup matching [Spree::Variant]

**Comment by kaesaeki** [comment]
It worked. Thank you very much!

**Comment by autotelik** [comment]
no worries, glad it worked for you !
