### ISSUE TITLE
how to upload order and users

### ISSUE THREAD

**Issue by shoaib-iqbal** [autotelik/datashift_spree#59]
there is rake task to upload users and orders?

**Comment by autotelik** [comment]
I have not needed to create specific loaders before for these. I would try with the generic 

thor datashift:import

tasks (csv or excel)

This worked for me : 

'''ruby
$ t datashift:export:csv -m Spree::Order -r /tmp/order.csv --remove number --remove-rails
Datashift: CSV export COMPLETED to /tmp/order.csv

$ t datashift:import:csv -m Spree::Order -i /tmp/order.csv
2	inbound rows were successfully processed.
There were NO failures.
```

If that does not work and you need some custom processing, I did write some specifics for importing shopify Order spreadsheets a while back, which may give you some pointers

 https://github.com/autotelik/datashift_spree/blob/master/lib/loaders/spree/shopify_order_migrator.rb

cheers
tom
