### ISSUE TITLE
Failed to import Products. Error: undefined method `type_cast_from_database'

### ISSUE THREAD

**Issue by LjuboF** [autotelik/datashift_spree#67]
#<NoMethodError: undefined method `type_cast_from_database' for #<ActiveRecord::ConnectionAdapters::PostgreSQLColumn:0x000000000edebe68>>

The same error is logged after trying to import with datashift_spree:load:products, and datashift:import.
Tried with CSV and XLS files.

My GemFile:
gem 'rails', '~> 5.0.7'
gem 'spree', '~> 3.2.7'
gem 'datashift', git: 'https://github.com/autotelik/datashift.git', :tag => 'v0.16.0'
gem 'datashift_spree', git: 'https://github.com/autotelik/datashift_spree.git', :branch => 'master'

**Comment by autotelik** [comment]
Hi

This relates to changes to active record adapters in Rails 5 - which should have been fixed in later versions of  datashift, so  please try removing the tag .

**Comment by LjuboF** [comment]
Hi, thank you for replying

Adding that tag was the only way to resolve dependencies between rails, datashift_spree, and datashift. Having most recent versions of Rails gives:

datashift_spree x64-mingw32 was resolved to 0.6.0, which depends on
      datashift x64-mingw32 was resolved to 0.40.0, which depends on
        rails (~> 4.2) x64-mingw32

And with Rails 4.2 I had problems between datashift and datashift_spree over a Paperclip dependency, I will try to show it here later, but i couldn't find a combination to work with Spree 3 to solve the issue that was closed in autotelik/datashift#57

**Comment by autotelik** [comment]
did you try

```
gem 'datashift', git: 'https://github.com/autotelik/datashift.git'
gem 'datashift_spree', git: 'https://github.com/autotelik/datashift_spree.git', :branch => 'feature/update_api_latest_ds_and_spree'
```

Unfortunately I don't work with Spree  day to day anymore, so I have only had time to keep the main datashift gem moving along, so maybe issues with later versions of Spree.

However the need for a separate gem may have been removed by better options in datashift.

If you could post your column headings and one example row of data I could maybe advise/document how to get the import going without the spree extensions

**Comment by autotelik** [comment]
I was getting warnings about paperclip being insecure so I bumped the version but perhaps I should  relax it in the gemspec so people can use what they need

**Comment by LjuboF** [comment]
maybe that would do it, I tried a lot of Rails, Spree, Datashift and Datashift_spree versions combinations just to try this gem and always was this paperclip dependency issue, and the one that passed had this "undefined method `type_cast_from_database'" Error, so maybe I didn´t find it but i think right now there´s not a way to use datashift_spree.

**Comment by LjuboF** [comment]
And yes, I was working with Datashift before, but tried this gem because of autotelik/datashift#57, I´m getting the same "price can´t be blank" error because the n-to-n relationship that Product have with Price in Spree 3. So I guess I'll have to use Datashift and import first only the Prices in a separate table, and then import Products specifying the price id in the "Prices" column, right?

**Comment by autotelik** [comment]
could you post your column headings and one example row of data  ??

I have a Spree 3.4 store I could use to quickly test and see whats going on

**Comment by LjuboF** [comment]
It's just the template for Spree::Product generated by datashift, from a fresh installation of Spree 3.2. With one row of the minimum data to import (sku, price, name, slug and a shipping category that already exists in the db), I copied and pasted the csv below:

sku,price,name,description,available_on,slug,meta_description,meta_keywords,tax_category_id,shipping_category_id,created_at,updated_at,promotionable,meta_title,discontinue_on,tax_category,shipping_category,master,taggings,base_tags,tag_taggings,tags,slugs,product_option_types,option_types,product_properties,properties,classifications,taxons,product_promotion_rules,promotion_rules,promotions,possible_promotions,variants,variants_including_master,stock_items,line_items,orders,variant_images
abc,100,test,test,,test,,,,,,,,,,,Por Defecto,,,,,,,,,,,,,,,,,,,,,,

**Comment by autotelik** [comment]
Thanks. So I have had a go at the process myself and pushed some changes to master **branch** of datashift that enables loading of basic product (no taxons, variants etc) 

The command line would be

bundle exec thor datashift:import:excel -i spree_product_import_3.4.5.xls -m Spree::Product -f sku price

My example spreadsheet attached

[spree_product_import_3.4.5.xlsx](https://github.com/autotelik/datashift_spree/files/1966966/spree_product_import_3.4.5.xlsx)

**Comment by LjuboF** [comment]
Yes, Product imports works for Spree 3 using https://github.com/autotelik/datashift master branch, tested under Spree 3.2 and Rails 5.0.7

Thanks.
